# Generated by Django 5.1.6 on 2025-03-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_favorite_influencers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='body_type',
            field=models.CharField(choices=[('hourglass', 'Hourglass'), ('pear', 'Pear'), ('athletic', 'Athletic'), ('rectangle', 'Rectangle'), ('petite', 'Petite')], help_text='Select your body type from the available options.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='brand_preferences',
            field=models.CharField(choices=[('zara', 'Zara'), ('hm', 'H&M'), ('ecochic', 'EcoChic'), ('urbanstyle', 'UrbanStyle'), ('luxuryline', 'LuxuryLine')], max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.CharField(choices=[('0_50', '$0 - $50'), ('50_100', '$50 - $100'), ('100_200', '$100 - $200'), ('200_plus', '$200+')], help_text='Select your typical budget range for fashion items.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='clothing_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_style',
            field=models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('bohemian', 'Bohemian'), ('sporty', 'Sporty'), ('business', 'Business')], max_length=20),
        ),
    ]
