# Generated by Django 5.1.6 on 2025-03-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='brand_preferences',
            field=models.CharField(help_text='Comma-separated list of brands', max_length=200),
        ),
    ]
