# Generated by Django 5.1.6 on 2025-03-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FashionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fashion_images/')),
                ('age_range', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=5)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('occasion', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
